<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R9JNNG2" failures="2" tests="2" name="testcases.AddCustomerTest" time="16.068" errors="0" timestamp="2023-02-08T17:19:47 IST" skipped="0">
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="5.494">
    <failure message="failed to add customer" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed to add customer
at org.testng.Assert.fail(Assert.java:110)
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <system-out>
    <![CDATA[Click on Bank_Manager_Login_Button
Click on Add_Customer_Button
Enter < test1 > in firstname
Enter < check1 > in lastname
Enter < 123456 > in postcode
Click on Add_Customer_Button
test passed
<a href=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_12_IST_2023.jpg>Screenshot</a>
<a href=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_12_IST_2023.jpg><img src=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_12_IST_2023.jpg height=100 width=100></img></a>]]>
  </system-out>
  <testcase classname="testcases.AddCustomerTest" name="addCustomer" time="10.574">
    <failure message="failed to add customer" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: failed to add customer
at org.testng.Assert.fail(Assert.java:110)
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addCustomer -->
  <system-out>
    <![CDATA[Click on Add_Customer_Button
Enter < test2 > in firstname
Enter < check2 > in lastname
Enter < 654321 > in postcode
Click on Add_Customer_Button
test passed
<a href=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_23_IST_2023.jpg>Screenshot</a>
<a href=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_23_IST_2023.jpg><img src=E:\eclipse\Workspace\ProjectOne\test-output\screenshots\addCustomer\Wed_Feb_08_17_19_23_IST_2023.jpg height=100 width=100></img></a>]]>
  </system-out>
</testsuite> <!-- testcases.AddCustomerTest -->
